---
# Will create defined lvm volumegroups
- name: Create volumegroups
  lvg:
    vg: "{{ item.vg }}"
    pvs: "{{ item.pvs }}"
    pesize: "{{ item.pesize }}"
  with_items: "{{ lvm_vgs }}"
  when: lvm_vgs is defined

# Will create defined lvm-volumes
- name: Create defined lvm volumes
  lvol:
    vg: "{{ item.vg }}"
    active: yes
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    opts: "{{ item.opts | default(omit) }}"
    state: present
  with_items: "{{ lvm_volumes }}"
  when:
    - lvm_volumes is defined
    - item.name is defined
    - item.vg is defined

